name: Deploy public to pokazon.ru

on:
  push:
    branches: [ main ]
    paths:
      - 'public/**'
      - '.github/workflows/deploy-public.yml'
  workflow_dispatch:

env:
  DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
  DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
  DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts

      - name: Ensure remote dir exists
        run: |
          ssh -i ~/.ssh/id_ed25519 "${DEPLOY_USER}@${DEPLOY_HOST}" \
            "mkdir -p '${DEPLOY_PATH}' && chown -R ${DEPLOY_USER}:${DEPLOY_USER} '${DEPLOY_PATH}'"

      - name: Rsync public/ to server
        run: |
          rsync -az --delete \
            -e "ssh -i ~/.ssh/id_ed25519" \
            public/ "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}/"
